package mendicoat_deck

var suites = []string{"H", "D", "C", "S"}
var ranks = []string{"2", "3", "4", "5", "6", "7", "8", "9", "10", "Jack", "Q", "K", "A"}

var cards = map[string]string{
	"2H":  "2 of Hearts",
	"3H":  "3 of Hearts",
	"4H":  "4 of Hearts",
	"5H":  "5 of Hearts",
	"6H":  "6 of Hearts",
	"7H":  "7 of Hearts",
	"8H":  "8 of Hearts",
	"9H":  "9 of Hearts",
	"10H": "10 of Hearts",
	"JH":  "Jack of Hearts",
	"QH":  "Queen of Hearts",
	"KH":  "King of Hearts",
	"AH":  "Ace of Hearts",
	"2D":  "2 of Diamonds",
	"3D":  "3 of Diamonds",
	"4D":  "4 of Diamonds",
	"5D":  "5 of Diamonds",
	"6D":  "6 of Diamonds",
	"7D":  "7 of Diamonds",
	"8D":  "8 of Diamonds",
	"9D":  "9 of Diamonds",
	"10D": "10 of Diamonds",
	"JD":  "Jack of  Diamonds",
	"QD":  "Queen of Diamonds",
	"KD":  "King of  Diamonds",
	"AD":  "Ace of   Diamonds",
	"2C":  "2 of Clubs",
	"3C":  "3 of Clubs",
	"4C":  "4 of Clubs",
	"5C":  "5 of Clubs",
	"6C":  "6 of Clubs",
	"7C":  "7 of Clubs",
	"8C":  "8 of Clubs",
	"9C":  "9 of Clubs",
	"10C": "10 of Clubs",
	"JC":  "Jack of Clubs",
	"QC":  "Queen of Clubs",
	"KC":  "King of Clubs",
	"AC":  "Ace of Clubs",
	"2S":  "2 of Spades",
	"3S":  "3 of Spades",
	"4S":  "4 of Spades",
	"5S":  "5 of Spades",
	"6S":  "6 of Spades",
	"7S":  "7 of Spades",
	"8S":  "8 of Spades",
	"9S":  "9 of Spades",
	"10S": "10 of Spades",
	"JS":  "Jack of Spades",
	"QS":  "Queen of Spades",
	"KS":  "King of Spades",
	"AS":  "Ace of Spades",
}
